version: '1.0'
models:
  - name: schemify
    description: schemify
    data_tests: schemify
    config:
      enabled: true
      alias: schemify
    meta: 
      owner: analytics
    columns:
      - name: schemify
        data_type: schemify
        description: schemify
        meta:
          gdpr_tags: schemify
